### ISSUE TITLE
Error adding an iCalendar link

### ISSUE THREAD

**Issue by InnovationBuddy** [humhub-contrib/external_calendar#47]
I just tried to add several different iCalendar links. However, an error occurs every single time "Error while creating iCal File. Please check, if Url is correct and Internet connection of server is enabled."

Does this error just occurs for me or is it the same problem for someone else, too? How can this problem be fixed?

**Comment by funkycram** [comment]
@luke- https://github.com/humhub-contrib/external_calendar/pull/49 should solve the problem (tested on an ICS file which wasn't working with version 2 of ics-parser and which is now working with version 3).

So you need to `composer update`

Moreover, the latest release solves depreciation warnings for PHP 8.2 (https://github.com/u01jmg3/ics-parser/releases)

**Comment by luke-** [comment]
@funkycram Thank you, I've merged and will release a new version
