### ISSUE TITLE
Remove humhub\widgets\ModalConfirm for Humhub 1.15

### ISSUE THREAD

**Issue by marc-farre** [humhub-contrib/external_calendar#53]
The module doesn't work on Humhub 1.15 because of `humhub\widgets\ModalConfirm` in https://github.com/humhub-contrib/external_calendar/blob/master/views/calendar/view.php

**Comment by ArchBlood** [comment]
Can be closed: https://github.com/humhub-contrib/external_calendar/commit/9473ab91e87555211de8f0a30ecba79721700ec3

**Comment by marc-farre** [comment]
@ArchBlood  Yes, thanks!
