### ISSUE TITLE
Add requirements.php

### ISSUE THREAD

**Issue by marc-farre** [humhub-contrib/external_calendar#69]
In anticipation on the new requirements.php support (https://github.com/humhub/humhub/issues/6744), this file could be created on this module regarding the Calendar module requirement.

@luke- I can create it if you want.

**Comment by luke-** [comment]
@marc-farre Yes please!

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub-contrib/external_calendar/pull/70
